CREATE TABLE IF NOT EXISTS roles (
  id   SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS music_type (
  id        SERIAL PRIMARY KEY,
  musictype VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
  id  SERIAL PRIMARY KEY,
  login    VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100)        NOT NULL,
  role_id  INTEGER             NOT NULL REFERENCES roles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS address (
  id       SERIAL PRIMARY KEY,
  postcode INTEGER      NOT NULL,
  city     VARCHAR(100) NOT NULL,
  street   VARCHAR(100) NOT NULL,
  home     VARCHAR(100) NOT NULL,
  user_id  INTEGER      NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE UNIQUE
);

CREATE TABLE IF NOT EXISTS user_musictype (
  user_id      INTEGER REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  musictype_id INTEGER REFERENCES music_type (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT user_musictype_pkey PRIMARY KEY (user_id, musictype_id)
)